# Generated by Django 5.2.11 on 2026-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Query'), ('booking', 'Booking & Cancellations'), ('tours', 'Tour Packages & Customization'), ('payments', 'Payments & Invoicing')], default='general', max_length=25)),
                ('order', models.IntegerField(default=0, help_text='Order in list display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=200)),
                ('tourist_name', models.CharField(blank=True, help_text='Name of the tourist (optional)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Location where it was shot (optional)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_designation', models.CharField(blank=True, help_text='E.g., Wanderer, Travel Blogger', max_length=100)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('testimonial_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('featured', models.BooleanField(default=True, help_text='Show on the home page testimonials list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Wanderlust', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload custom site logo', null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='info@wanderlust.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (234) 567-890', max_length=20)),
                ('address', models.TextField(default='123 Luxury Travel Way, Wander City, WC 54321')),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Provide Google Maps iframe src URL. E.g. https://www.google.com/maps/embed?pb=...')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com')),
                ('about_summary', models.TextField(default='Wanderlust is a premier travel boutique designing bespoke journeys across the globe. We elevate travel experiences with curated destinations, luxury lodgings, and meticulous tour management.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
