# Generated by Django 5.2.11 on 2026-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this destination on the home page spotlight'),
        ),
    ]
